"""
B2-2 option c: Pure C layer unit tests for runtime_typed.c

This test file compiles a standalone C program that directly calls
dv_socket_*, dv_poller_*, dv_scheduler_run_event_loop WITHOUT going
through LLVM IR generation. It gives the C runtime a real green
independent of the codegen pipeline.

Compilation uses clang (preferred) or MSVC as fallback.
The echo server is a plain Python TCP echo server on port 19150-19159.

Verification path evaluation (B2-2 three options):
  a) Install llvmlite: Already installed (v0.49.0). This enables the MCJIT
     in-process execution path, but alone does not verify the full compile
     chain (.light -> IR -> native binary -> run). llvmlite is a toolchain
     dependency, not a test-object dependency, so installing it is allowed.
  b) clang direct compile: CHOSEN. clang compiles .ll + runtime_typed.c
     into a standalone exe, which is the closest to real release form.
     Already working: tests/test_llvm_net.py 10/10 pass via this path.
  c) Pure C unit tests: DONE (this file). Tests the C runtime directly
     without IR generation, catching bugs that might be masked by the
     specific IR patterns generated by codegen.

Choice: b + c. Why not a alone: MCJIT in-process execution is less
realistic than a standalone binary; it also requires llvmlite which may
not be present on all machines. Why not b alone: the C runtime functions
might have bugs not triggered by the specific IR patterns; direct C
testing catches those.
"""
import sys
import os
import socket
import threading
import subprocess
import time
import shutil
import pytest

# Reuse the compiler detection from test_llvm_net
sys.path.insert(0, os.path.dirname(__file__))
from test_llvm_net import _find_clang_safely, _find_msvc_safely

CLANG_PATH = _find_clang_safely()
MSVC_VCVARS = _find_msvc_safely()
HAS_CLANG = CLANG_PATH is not None
HAS_MSVC = MSVC_VCVARS is not None

skip_no_compiler = pytest.mark.skipif(
    not (HAS_CLANG or HAS_MSVC),
    reason="缺 clang 和 MSVC: C 层单元测试无法编译, dv_socket_*/dv_poller_*/dv_scheduler 行为全部未验证"
)

C_TEST_SOURCE = os.path.join(os.path.dirname(__file__), 'test_llvm_c_runtime.c')
RUNTIME_C = os.path.join(os.path.dirname(__file__), '..', 'src', 'llvm', 'runtime_typed.c')
EXE_PATH = os.path.join(os.path.dirname(__file__), '_taskB2_c_test.exe')


class EchoServer:
    """Simple TCP echo server for C unit tests"""

    def __init__(self, port):
        self.port = port
        self._sock = None
        self._thread = None
        self._stop = False

    def start(self):
        self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._sock.bind(('127.0.0.1', self.port))
        self._sock.listen(5)
        self._sock.settimeout(0.5)
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        time.sleep(0.1)

    def _run(self):
        while not self._stop:
            try:
                conn, addr = self._sock.accept()
                conn.settimeout(5.0)
                t = threading.Thread(target=self._handle, args=(conn,), daemon=True)
                t.start()
            except socket.timeout:
                continue
            except OSError:
                break

    def _handle(self, conn):
        try:
            while not self._stop:
                data = conn.recv(4096)
                if not data:
                    break
                conn.sendall(data)
        except (socket.timeout, ConnectionError, OSError):
            pass
        finally:
            conn.close()

    def stop(self):
        self._stop = True
        if self._sock:
            try:
                self._sock.close()
            except Exception:
                pass
        if self._thread:
            self._thread.join(timeout=2)


def _compile_c_test(extra_args=(), out_path=None):
    """Compile the C test program. Returns True on success.

    B2-4: runtime_typed.c 现在引用 Schannel/证书链 API，链接必须带
    secur32/crypt32，否则一定报未解析符号。
    """
    exe = out_path or EXE_PATH
    if HAS_CLANG:
        cmd = [CLANG_PATH, '-O2', '-o', exe, C_TEST_SOURCE,
               '-D_CRT_SECURE_NO_WARNINGS']
        cmd.extend(extra_args)
        cmd.extend(['-lws2_32', '-lsecur32', '-lcrypt32'])
        result = subprocess.run(
            cmd,
            capture_output=True, text=True, encoding='utf-8', errors='replace',
            timeout=60
        )
        if result.returncode != 0:
            print(f"clang compile failed:\n{result.stderr[:2000]}")
            return False
        return True
    elif HAS_MSVC:
        extra = ' '.join(extra_args)
        bat_content = f"""@echo off
chcp 65001 >nul 2>&1
call "{MSVC_VCVARS}" x64 >nul 2>&1
cl.exe /nologo /O2 /utf-8 /D_CRT_SECURE_NO_WARNINGS {extra} "{C_TEST_SOURCE}" /Fe:"{exe}" /link ws2_32.lib secur32.lib crypt32.lib 2>&1
echo EXIT_CODE=%ERRORLEVEL%
"""
        bat_path = os.path.join(os.path.dirname(__file__), '_taskB2_compile_c.bat')
        with open(bat_path, 'w', encoding='utf-8') as f:
            f.write(bat_content)
        try:
            result = subprocess.run(
                ['cmd', '/c', bat_path],
                capture_output=True, text=True, encoding='utf-8', errors='replace',
                timeout=60
            )
            if result.returncode != 0 or 'EXIT_CODE=0' not in result.stdout:
                print(f"MSVC compile failed:\n{result.stdout[:2000]}\n{result.stderr[:2000]}")
                return False
        finally:
            try:
                os.remove(bat_path)
            except Exception:
                pass
            # Clean MSVC temp files
            for suffix in ['.obj']:
                p = EXE_PATH.replace('.exe', suffix)
                try:
                    if os.path.exists(p):
                        os.remove(p)
                except Exception:
                    pass
        return True
    return False


@skip_no_compiler
class TestCLayerUnit:
    """B2-2 option c: Pure C layer unit tests"""

    def test_c_runtime_socket_poller(self):
        """Compile and run C unit tests for socket/poller/event loop"""
        # Compile
        assert _compile_c_test(), "C test compilation failed"
        assert os.path.exists(EXE_PATH), f"Exe not found: {EXE_PATH}"

        # Start echo server
        port = 19150
        server = EchoServer(port)
        server.start()
        try:
            # Run C test
            result = subprocess.run(
                [EXE_PATH, str(port)],
                capture_output=True, text=True, encoding='utf-8', errors='replace',
                timeout=30
            )

            print(result.stdout)
            if result.stderr:
                print(f"stderr: {result.stderr[:1000]}")

            # Check all tests passed
            assert result.returncode == 0, \
                f"C unit tests failed (exit {result.returncode}):\n{result.stdout}"

            # Verify output contains expected test results
            assert '[PASS]' in result.stdout, "No PASS in output"
            assert '[FAIL]' not in result.stdout, \
                f"Failures found:\n{result.stdout}"
            assert 'passed' in result.stdout, "No summary in output"

        finally:
            server.stop()
            # Clean up exe
            try:
                if os.path.exists(EXE_PATH):
                    os.remove(EXE_PATH)
            except Exception:
                pass

    def test_c_runtime_compiles_clean(self):
        """Verify the C test file compiles without warnings (clang only)"""
        if not HAS_CLANG:
            pytest.skip("缺 clang: -Wall 编译警告检查未验证")

        result = subprocess.run(
            [CLANG_PATH, '-Wall', '-Wextra', '-c', '-o', os.devnull,
             C_TEST_SOURCE],
            capture_output=True, text=True, encoding='utf-8', errors='replace',
            timeout=60
        )
        # runtime_typed.c may have some warnings, but our test file should be clean
        # We check that our test file itself doesn't introduce errors
        assert result.returncode == 0, \
            f"Compilation errors:\n{result.stderr[:2000]}"


if __name__ == '__main__':
    pytest.main([__file__, '-v', '-s'])
